### PR TITLE
Added module for Split Payments extension 

### PR DESCRIPTION
**Pull request by jimasuen**
Added module for Split Payments extension. Module allows you to:

- Get list of target wallets
- Add target wallets
- Delete all target wallets

P.S.
Also added test examples for pay lnurl and paylnaddress in test_userwallet.py (To-do in #142)

### CODE REVIEW

**Comment by bitkarrot** [comment]
Thanks for your pull request. I'm asking a few to test it and will get back to you soon

**Comment by bitkarrot** [comment]
@Mccalabrese, please review. thanks

**Comment by bitkarrot** [comment]
Bump. @Mccalabrese

**Comment by Mccalabrese** [comment]
Split payments test ran successfully 👍

**Comment by bitkarrot** [comment]
@jimasuen i have just been slow here; sorry about that. let me see if i can get this merged in today

**Review by bitkarrot — APPROVED** [review]

**Pull request merged**
